### PR TITLE
Request to merge milestone 2 (user interface feature) to development branch

### PR DESCRIPTION
**Pull request by VanessaAoki**
This is the branch for Milestone 2 (user interface) in the Tic Tac Toe ruby project.

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

#### Hey  **@VanessaAoki **,  your project is looking really good, however, in order to have this project accepted, you're required to do these changes, listed below:
- [x]  game asks the player to select from available moves
- [x] game informs player if the selected move is invalid (without computing what an invalid move is)
- [x] game informs player if the selected move is a winning move (without computing the winning move)
- [x] A loop is needed in this game (recommended is `while` but anything else will do ([OdinProject hint]
(https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
- [x] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
````
### **Please make the required changes and submit another review request when you are ready.**

<hr>
### if you have any question kindly reach me on slack @GzimAsani

### HAPPY CODING :computer:

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @VanessaAoki and @DsunilK :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] game asks the player to select from available moves. Your game asks the player to select a move but there are no available moves to select from until the player inputs a number. Kindly fix that.
image
image
* [x] game displays board after the player move (without computing which spots on the board are taken). You only displayed an array of numbers, not the board.
image
* [x] game informs player if the selected move is a winning move (without computing the winning move)
* [x] game informs player if the selected move is a draw move (without computing draw)
* [x] game repeats all actions for the next player's move

### Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

#### Hey  **Team**,  your project is looking really good, and great job implementing all the requirements from previous reviewer, however I am sorry but I have to ask you to implement one more thing:
Currently your game displays first user as the winner no matter what and that is fine but I want you to implement that the game may end also as draw, you do not need to implement any logic just add a case when when the game ends as a draw

- [REQUIRED] game informs player if the selected move is a draw move (without computing draw)
- [REQUIRED] Rubocop is failing locally so please fix them

<hr>
### if you have any question kindly reach me on slack @GzimAsani

### HAPPY CODING :computer:

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED!! :recycle: 
-------
Hello team!! :wave:  you are working really hard on this project :muscle: great job :+1: 
I really love that the game asks if the players know how to play.
However, there are a few changes to make :wrench: 
-------------

- [x] Check your counter, I can put my move in the same place 9 times, and the game finished. The game should continue till all places are taken. 
- [x] Also the game informs the player if the selected move is invalid (without computing what an invalid move is)
-------------
Made the required changes :hammer_and_wrench: and send it for another review :+1: 
HAPPY CODING!!! :smile:

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Required Changes ♻🛑**

<hr>

Hello there, great work you've done so far on this milestone and on the previous required changes. However, there is still one small change to make before moving on to the next!

- [x] Please make sure that your game is informing an invalid move on the first time (I have to put the same move again in order to tell me that it's an invalid move, and this is turning the player's turn, so it doesn't make sense. Please fix this issue and you'll be good to go)

Good luck and happy coding 👨‍💻💻😊

**Review by mke2111 — APPROVED** [review]
# **🥇 🥇  STATUS: APPROVED 🥇 🥇** 

Congratulations @VanessaAoki  and  @DsunilK, I applaud you for the splendid job done on this project. Keep up the efforts.

You may merge to the development branch and remember to submit a project completion form.

### Cheers 👍🏽 👍🏽 

**Slack: Roy Mukuye**

**Pull request merged**
